automation:
  - alias: "Luzes baseadas em presenca"
    id: "luzes_baseadas_em_presenca"
    trigger:
      - platform: state
        entity_id: input_boolean.ninguem_em_casa
        from: "on"
        to: "off"
        id: "alguem_chegou_em_casa"
      - platform: state
        entity_id: input_boolean.ninguem_em_casa
        from: "off"
        to: "on"
        id: "ninguem_em_casa"
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: sun
                    after: sunset
                    after_offset: "-01:00:00"
                  - condition: trigger
                    id: "alguem_chegou_em_casa"
            sequence:
              - service: light.turn_on
                entity_id: light.sala_de_estar
          - conditions:
              - condition: trigger
                id: "ninguem_em_casa"
            sequence:
              - service: light.turn_off
                entity_id: light.todas_as_luzes

  - alias: "Luz do Escritório baseada em presença"
    id: "luz_escritorio_baseada_em_presenca"
    trigger:
      - platform: state
        entity_id: binary_sensor.presenca_escritorio_occupancy
        from: "on"
        to: "off"
        for: 
          minutes: 3
        id: "ninguem_no_escritório"
      - platform: state
        entity_id: binary_sensor.presenca_escritorio_occupancy
        from: "off"
        to: "on"
        id: "alguem_no_escritorio"
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: sun
                    after: sunset
                    after_offset: "-01:00:00"
                  - condition: numeric_state
                    entity_id: sensor.presenca_escritorio_illuminance_lux
                    below: 5
                  - condition: trigger
                    id: "alguem_no_escritorio"
            sequence:
              - service: light.turn_on
                entity_id: light.office_light
          - conditions:
              - condition: trigger
                id: "ninguem_no_escritório"
            sequence:
              - service: light.turn_off
                entity_id: light.office_light

  - alias: "Luz da Escada baseada em presença"
    id: "luz_escada_baseada_em_presenca"
    trigger:
      - platform: state
        entity_id: binary_sensor.presenca_escada
        from: "on"
        to: "off"
        id: "ninguem_na_escada"
      - platform: state
        entity_id: binary_sensor.presenca_escada
        from: "off"
        to: "on"
        id: "alguem_na_escada"
    action:
      - choose:
          - conditions:
              - condition: and
                conditions:
                  - condition: trigger
                    id: "alguem_na_escada"
            sequence:
              - service: light.turn_on
                entity_id: light.escada
          - conditions:
              - condition: trigger
                id: "ninguem_na_escada"
            sequence:
              - service: light.turn_off
                entity_id: light.escada

  - alias: "Teste Feeder 1"
    id: "test_feeder_1"
    trigger:
      platform: state
      entity_id: input_number.feeder_1_motor_control
    action:
      - service: esphome.cat_feeder_1_control_stepper
        data_template:
          target: "{{trigger.to_state.state | int}}"

  - alias: "Teste Feeder 2"
    id: "test_feeder_2"
    trigger:
      platform: state
      entity_id: input_number.feeder_1_motor_control
    action:
      - service: esphome.cat_feeder_1_control_stepper
        data:
          target: 400
      - service: esphome.cat_feeder_1_control_stepper
        data:
          target: 800