
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

homeassistant:
  packages: !include_dir_named packages

#light groups
light: !include packages/lightning/groups.yaml
