group:
  alguem_em_casa:
    name: Alguém está em casa
    entities:
      - person.vinicius
      - person.mariana
    all: false

device_tracker:
  - platform: ping
    hosts:
      ping_iphone_mari: !secret mari_iphone_ip_addr
      ping_iphone_vini: !secret vini_iphone_ip_addr
    count: 2
    consider_home: 60

input_boolean:
  notify_home:
    name: Notify when someone arrives home
    icon: mdi:car
  ninguem_em_casa:
    name: Ninguém em casa
    icon: mdi:account-multiple-minus

automation:
  - alias: "Presença: Chegando e saindo de casa"
    trigger:
      - platform: state
        entity_id: group.alguem_em_casa
        from: "not_home"
        to: "home"
        id: alguem_chegou_em_casa
      - platform: state
        entity_id: group.alguem_em_casa
        from: "home"
        to: "not_home"
        id: ninguem_em_casa

    action:
      - choose:
          # IF alguem chegou em casa
          - conditions:
              - condition: trigger
                id: "alguem_chegou_em_casa"
            sequence:
              - service: input_boolean.turn_off
                entity_id: input_boolean.ninguem_em_casa
          - conditions:
              - condition: trigger
                id: "ninguem_em_casa"
            sequence:
              - service: input_boolean.turn_on
                entity_id: input_boolean.ninguem_em_casa
